site_name: 'CompbioZurich'
site_description: 'Computational Biology & Bioinformatics in the Zürich Area'
site_author: Michael Baudis
copyright: '&copy; 2023 Michael Baudis'
repo_name: 'compbiozurich.github.io'

repo_url: https://github.com/compbiozurich/compbiozurich.github.io
edit_uri: edit/main/docs/

this_year: 2023

###############################################################################

nav:
  - 'General Information': index.md
  - News & Events: news
  - Bioinformatics Groups: contacts
  - Lectures, Courses & Graduate Programs:
    - Overview: teaching
    - UZH BIO390: UZH-BIO390/
    - UZH BIO392: UZH-BIO392/
  - Community Resources:
    - Tools & Resources: resources
    - Positions: positions

###############################################################################

plugins:
  - search
  - macros

markdown_extensions:
  - toc
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.saneheaders
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - extra/.icons

###############################################################################

theme:
  name: material
  palette:
    primary: white
    accent: white
  favicon: img/favicon.ico
  logo: img/site_logo.png
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/list-ordered-24
  features:
    - content.tabs.link
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
  custom_dir: extra
      
extra:
  news:
    dir: news
    author: mbaudis
    list_length: 50
    extended_preview: true
    excerpt_separator: <!--more-->
  contacts:
    dir: contacts
    author: mbaudis
    list_length: 50
    extended_preview: true
    excerpt_separator: <!--more-->
  resources:
    dir: resources
    author: mbaudis
    list_length: 50
    extended_preview: true
    excerpt_separator: <!--more-->
  teaching:
    dir: teaching
    author: mbaudis
    list_length: 50
    extended_preview: true
    excerpt_separator: <!--more-->
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/mbaudis
extra_css:
  - css/theme_overrides.css
